### ISSUE TITLE
suitable for listserv?

### ISSUE THREAD

**Issue by pzybe** [rtertiaer/mailfruit#1]
I think I asked you this a long while ago but would this be suitable for a listserv (mailing list)?

**Comment by rtertiaer** [comment]
@ptdel I totally missed this in the deluge of github issues (recently went on an unwatching purge...) I don't think this is valid for a listserv, because it encompasses both the Mail Transfer Agent (Postfix) and Mail Delivery Agent (Dovecot) roles, and notably stores emails for users. If you wanted to set up a listserv, you'd only want to set up a Mail Transfer Agent, and then some software to "replay" the mail across a list of subscribers.

I've used GNU Mailman in the past and it's :heart_eyes_cat: It's well maintained, simple to setup, super malleable (it's written in python) and iirc self-contained - no need to set up an external MTA.
